[build]
  # Comando estÃ¡ndar de Astro
  command = "npm run build"
  # Carpeta donde Astro tira el HTML
  publish = "dist"

[functions]
  # ğŸ‘ˆ ESTO ES LO IMPORTANTE
  # Le decimos explÃ­citamente dÃ³nde buscar las funciones
  directory = "netlify/functions"